<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Add new album test';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
    <div class="col-sm-4">
    <div class="form-group">
    <form method="POST" action="">
    <label for="exampleInputEmail1">Title</label>
    <input type="hidden" name="id"  id="">
    <input type="text" class="form-control" name="title" id="exampleInputEmail1" aria-describedby="emailHelp"  placeholder="Enter Title" required>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>

  <!-- am here -->
  <div class="form-group">
    <label for="exampleInputPassword1">Artist</label>
    <input type="text" class="form-control" id="exampleInputPassword1" name="artist" placeholder=" Enter artist" required>
  </div>
  <button type="submit" name="submit" class="btn btn-primary">Submit</button>
</form>
