<?php
 // module/Album/view/album/album/delete.phtml:

 $title = 'Delete album';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
    <span class="badge badge-pill badge-primary">
    <?php echo $this->escapeHtml($album->title); ?>
    </span>  by
    <span class="badge badge-pill badge-primary">
    <?php echo $this->escapeHtml($album->artist); ?>
    </span>
     ?
 </p>
 
 <?php
 $url = $this->url('album', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $album->id; ?>" />
     <input type="submit"class="btn btn-danger btn-sm"  name="del" value="Yes" />
     <input type="submit" class="btn btn-primary btn-sm" name="del" value="No" />
 </div>
 </form>