<?php

 $title = 'Edit album';
 $this->headTitle($title);
//  echo "<pre >";
//  var_dump($this->form);
//  echo "</pre>";


 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <div class="col-sm-4">
    <div class="form-group">
    <form method="POST" action="">
    <label for="exampleInputEmail1">Title</label>
    <input type="hidden" name="id" value="<?php echo $this->form->get('id')->getValue(); ?>"  id="">
    <input type="text" class="form-control" name="title" id="exampleInputEmail1" aria-describedby="emailHelp"  value="<?php echo $this->form->get('title')->getValue(); ?>"  placeholder="Enter Title" required>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Artist</label>
    <input type="text" class="form-control" id="exampleInputPassword1" name="artist" value="<?php echo $this->form->get('artist')->getValue(); ?>" placeholder=" Enter artist" required>
  </div>
  <button type="submit" name="submit" class="btn btn-primary">Submit</button>
</form>
